In [1]:
import pandas as pd

dados_2012 = pd.read_csv(
    "Tabela5-sem_emprego_2012.csv",
    sep=";",
    decimal=","
).rename(columns={
    "Desocupados - homens (2012 T1)": "homens_2012",
    "Desocupados - mulheres (2012 T1)": "mulheres_2012"
})

dados_2026 = pd.read_csv(
    "Tabela5-sem_emprego_2026.csv",
    sep=";",
    decimal=","
).rename(columns={
    "Desocupados - homens (2026 T1)": "homens_2026",
    "Desocupados - mulheres (2026 T1)": "mulheres_2026"
})

In [2]:
chaves = ["Sigla", "Código", "Estado"]

comparacao = pd.merge(
    dados_2012,
    dados_2026,
    on=chaves,
    how="inner"
)

comparacao["mudanca_homens"] = (
    comparacao["homens_2026"] - comparacao["homens_2012"]
)

comparacao["mudanca_mulheres"] = (
    comparacao["mulheres_2026"] - comparacao["mulheres_2012"]
)

comparacao

,Sigla,Código,Estado,homens_2012,mulheres_2012,homens_2026,mulheres_2026,mudanca_homens,mudanca_mulheres
0,AC,12,Acre,45.3,54.7,53.2,46.8,7.9,-7.9
1,AL,27,Alagoas,44.7,55.3,50.7,49.3,6.0,-6.0
2,AM,13,Amazonas,47.5,52.5,46.8,53.2,-0.7,0.7
3,AP,16,Amapá,48.1,51.9,51.1,48.9,3.0,-3.0
4,BA,29,Bahia,43.8,56.2,44.7,55.3,0.9,-0.9
5,CE,23,Ceará,51.1,48.9,52.7,47.3,1.6,-1.6
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1,6.9,-6.9
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5,1.1,-1.1
8,GO,52,Goiás,41.0,59.0,47.5,52.5,6.5,-6.5
9,MA,21,Maranhão,47.2,52.8,49.1,50.9,1.9,-1.9
10,MG,31,Minas Gerais,43.1,56.9,48.6,51.4,5.5,-5.5
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,-1.9,1.9
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,-1.3,1.3
13,PA,15,Pará,43.2,56.8,48.3,51.7,5.1,-5.1
14,PB,25,Paraíba,44.4,55.6,48.9,51.1,4.5,-4.5
15,PE,26,Pernambuco,43.9,56.1,48.7,51.3,4.8,-4.8
16,PI,22,Piauí,51.2,48.8,55.1,44.9,3.9,-3.9
17,PR,41,Paraná,40.3,59.7,46.3,53.7,6.0,-6.0
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,1.2,-1.2
19,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8,-2.8,2.8
20,RO,11,Rondônia,43.4,56.6,33.0,67.0,-10.4,10.4
21,RR,14,Roraima,41.8,58.2,43.4,56.6,1.6,-1.6
22,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6,4.6,-4.6
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,1.9,-1.9
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,-6.2,6.2
25,SP,35,São Paulo,45.4,54.6,46.2,53.8,0.8,-0.8
26,TO,17,Tocantins,55.3,44.7,46.2,53.8,-9.1,9.1

In [3]:
chaves = ["Sigla", "Código", "Estado"]

comparacao = pd.merge(
    dados_2012,
    dados_2026,
    on=chaves,
    how="inner"
)

comparacao["mudanca_homens"] = (
    comparacao["homens_2026"] - comparacao["homens_2012"]
)

comparacao["mudanca_mulheres"] = (
    comparacao["mulheres_2026"] - comparacao["mulheres_2012"]
)

comparacao

,Sigla,Código,Estado,homens_2012,mulheres_2012,homens_2026,mulheres_2026,mudanca_homens,mudanca_mulheres
0,AC,12,Acre,45.3,54.7,53.2,46.8,7.9,-7.9
1,AL,27,Alagoas,44.7,55.3,50.7,49.3,6.0,-6.0
2,AM,13,Amazonas,47.5,52.5,46.8,53.2,-0.7,0.7
3,AP,16,Amapá,48.1,51.9,51.1,48.9,3.0,-3.0
4,BA,29,Bahia,43.8,56.2,44.7,55.3,0.9,-0.9
5,CE,23,Ceará,51.1,48.9,52.7,47.3,1.6,-1.6
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1,6.9,-6.9
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5,1.1,-1.1
8,GO,52,Goiás,41.0,59.0,47.5,52.5,6.5,-6.5
9,MA,21,Maranhão,47.2,52.8,49.1,50.9,1.9,-1.9
10,MG,31,Minas Gerais,43.1,56.9,48.6,51.4,5.5,-5.5
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,-1.9,1.9
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,-1.3,1.3
13,PA,15,Pará,43.2,56.8,48.3,51.7,5.1,-5.1
14,PB,25,Paraíba,44.4,55.6,48.9,51.1,4.5,-4.5
15,PE,26,Pernambuco,43.9,56.1,48.7,51.3,4.8,-4.8
16,PI,22,Piauí,51.2,48.8,55.1,44.9,3.9,-3.9
17,PR,41,Paraná,40.3,59.7,46.3,53.7,6.0,-6.0
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,1.2,-1.2
19,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8,-2.8,2.8
20,RO,11,Rondônia,43.4,56.6,33.0,67.0,-10.4,10.4
21,RR,14,Roraima,41.8,58.2,43.4,56.6,1.6,-1.6
22,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6,4.6,-4.6
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,1.9,-1.9
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,-6.2,6.2
25,SP,35,São Paulo,45.4,54.6,46.2,53.8,0.8,-0.8
26,TO,17,Tocantins,55.3,44.7,46.2,53.8,-9.1,9.1

In [4]:
bruto = pd.read_excel(
    "Tabela 1.1.1.xls",
    sheet_name=0,
    header=None,
    skiprows=8,
    nrows=33
)

horas_estado = bruto.iloc[:, [0, 1, 4, 5, 6, 7]].copy()

horas_estado.columns = [
    "Estado",
    "media_horas_2022",
    "horas_homens_brancos",
    "horas_homens_pretos_pardos",
    "horas_mulheres_brancas",
    "horas_mulheres_pretas_pardas"
]

horas_estado = horas_estado[
    horas_estado["Estado"].isin(comparacao["Estado"])
].copy()

colunas_numericas = horas_estado.columns[1:]

horas_estado[colunas_numericas] = horas_estado[
    colunas_numericas
].apply(pd.to_numeric, errors="coerce")

horas_estado

,Estado,media_horas_2022,horas_homens_brancos,horas_homens_pretos_pardos,horas_mulheres_brancas,horas_mulheres_pretas_pardas
2,Rondônia,17.014162,12.111127,12.544080,20.412887,21.061410
3,Acre,13.606903,10.796120,9.686983,16.130352,16.710754
4,Amazonas,16.807290,12.233043,12.822584,18.764969,20.716986
5,Roraima,13.639257,10.814803,10.476601,16.135877,16.560244
6,Pará,16.474268,11.524306,11.026707,19.835110,21.591144
7,Amapá,13.586656,11.116821,10.749444,16.648579,15.908487
8,Tocantins,15.815781,10.733863,11.682616,19.663713,19.629399
10,Maranhão,16.669614,11.665173,11.437359,19.881056,20.739589
11,Piauí,17.960366,12.258324,11.204814,20.494063,23.695440
12,Ceará,19.499293,12.186936,12.821323,23.019718,24.952274
13,Rio Grande do Norte,18.307740,11.166909,11.086286,23.547080,24.422884
14,Paraíba,18.920816,12.480204,12.400831,23.642936,24.035650
15,Pernambuco,19.306249,12.312833,12.868821,23.357880,24.243396
16,Alagoas,20.217129,12.121839,13.357160,24.093655,25.856637
17,Sergipe,18.826541,10.830511,11.270341,21.740902,25.637681
18,Bahia,17.849776,10.551673,10.982808,22.572730,23.217119
20,Minas Gerais,17.502141,11.319720,11.619120,22.186650,23.075751
21,Espírito Santo,17.111106,11.798571,12.017589,20.464462,22.196626
22,Rio de Janeiro,16.716263,12.000036,12.864896,19.203741,20.957728
23,São Paulo,17.071295,12.123044,12.235200,20.771186,21.767620
25,Paraná,15.390122,11.240085,10.815611,18.896661,19.365380
26,Santa Catarina,16.039355,12.339052,11.517342,19.414764,19.646573
27,Rio Grande do Sul,15.356709,11.308447,11.519941,18.868230,19.107720
29,Mato Grosso do Sul,15.309783,10.446213,11.126920,18.593200,19.542761
30,Mato Grosso,14.239989,9.479654,9.265734,17.782825,18.695923
31,Goiás,15.186471,10.636424,10.531883,18.440842,19.587913
32,Distrito Federal,15.096351,11.377952,10.481279,17.738123,19.307332

In [5]:
resultado_alice = comparacao.merge(
    horas_estado,
    on="Estado",
    how="inner"
)

resultado_alice = resultado_alice.sort_values(
    "Estado"
).reset_index(drop=True)

resultado_alice.to_csv(
    "geral_alice.csv",
    sep=";",
    decimal=",",
    index=False
)

print(f"{len(resultado_alice)} estados foram unidos")

resultado_alice

27 estados foram unidos

,Sigla,Código,Estado,homens_2012,mulheres_2012,homens_2026,mulheres_2026,mudanca_homens,mudanca_mulheres,media_horas_2022,horas_homens_brancos,horas_homens_pretos_pardos,horas_mulheres_brancas,horas_mulheres_pretas_pardas
0,AC,12,Acre,45.3,54.7,53.2,46.8,7.9,-7.9,13.606903,10.796120,9.686983,16.130352,16.710754
1,AL,27,Alagoas,44.7,55.3,50.7,49.3,6.0,-6.0,20.217129,12.121839,13.357160,24.093655,25.856637
2,AP,16,Amapá,48.1,51.9,51.1,48.9,3.0,-3.0,13.586656,11.116821,10.749444,16.648579,15.908487
3,AM,13,Amazonas,47.5,52.5,46.8,53.2,-0.7,0.7,16.807290,12.233043,12.822584,18.764969,20.716986
4,BA,29,Bahia,43.8,56.2,44.7,55.3,0.9,-0.9,17.849776,10.551673,10.982808,22.572730,23.217119
5,CE,23,Ceará,51.1,48.9,52.7,47.3,1.6,-1.6,19.499293,12.186936,12.821323,23.019718,24.952274
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1,6.9,-6.9,15.096351,11.377952,10.481279,17.738123,19.307332
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5,1.1,-1.1,17.111106,11.798571,12.017589,20.464462,22.196626
8,GO,52,Goiás,41.0,59.0,47.5,52.5,6.5,-6.5,15.186471,10.636424,10.531883,18.440842,19.587913
9,MA,21,Maranhão,47.2,52.8,49.1,50.9,1.9,-1.9,16.669614,11.665173,11.437359,19.881056,20.739589
10,MT,51,Mato Grosso,44.1,55.9,42.8,57.2,-1.3,1.3,14.239989,9.479654,9.265734,17.782825,18.695923
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7,-1.9,1.9,15.309783,10.446213,11.126920,18.593200,19.542761
12,MG,31,Minas Gerais,43.1,56.9,48.6,51.4,5.5,-5.5,17.502141,11.319720,11.619120,22.186650,23.075751
13,PR,41,Paraná,40.3,59.7,46.3,53.7,6.0,-6.0,15.390122,11.240085,10.815611,18.896661,19.365380
14,PB,25,Paraíba,44.4,55.6,48.9,51.1,4.5,-4.5,18.920816,12.480204,12.400831,23.642936,24.035650
15,PA,15,Pará,43.2,56.8,48.3,51.7,5.1,-5.1,16.474268,11.524306,11.026707,19.835110,21.591144
16,PE,26,Pernambuco,43.9,56.1,48.7,51.3,4.8,-4.8,19.306249,12.312833,12.868821,23.357880,24.243396
17,PI,22,Piauí,51.2,48.8,55.1,44.9,3.9,-3.9,17.960366,12.258324,11.204814,20.494063,23.695440
18,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8,-2.8,2.8,18.307740,11.166909,11.086286,23.547080,24.422884
19,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6,4.6,-4.6,15.356709,11.308447,11.519941,18.868230,19.107720
20,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6,1.2,-1.2,16.716263,12.000036,12.864896,19.203741,20.957728
21,RO,11,Rondônia,43.4,56.6,33.0,67.0,-10.4,10.4,17.014162,12.111127,12.544080,20.412887,21.061410
22,RR,14,Roraima,41.8,58.2,43.4,56.6,1.6,-1.6,13.639257,10.814803,10.476601,16.135877,16.560244
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4,1.9,-1.9,16.039355,12.339052,11.517342,19.414764,19.646573
24,SE,28,Sergipe,46.5,53.5,40.3,59.7,-6.2,6.2,18.826541,10.830511,11.270341,21.740902,25.637681
25,SP,35,São Paulo,45.4,54.6,46.2,53.8,0.8,-0.8,17.071295,12.123044,12.235200,20.771186,21.767620
26,TO,17,Tocantins,55.3,44.7,46.2,53.8,-9.1,9.1,15.815781,10.733863,11.682616,19.663713,19.629399